name       : libmhash
version    : 0.9.9.9
release    : 2
source     :
    - https://sourceforge.net/projects/mhash/files/mhash/0.9.9.9/mhash-0.9.9.9.tar.bz2 : 56521c52a9033779154432d0ae47ad7198914785265e1f570cee21ab248dfef0
homepage   : http://mhash.sourceforge.net/
license    : GPL-2.0-or-later
component  : security.library
summary    : The mhash library provides an easy way to access strong hashes,
description: |
    The mhash library provides an easy way to access strong hashes such as MD5, SHA1 and other algorithms.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
