name       : libmhash
version    : 0.9.9.9
release    : 1
source     :
    - http://heanet.dl.sourceforge.net/project/mhash/mhash/0.9.9.9/mhash-0.9.9.9.tar.gz : 3dcad09a63b6f1f634e64168dd398e9feb9925560f9b671ce52283a79604d13e
license    : GPL-2.0
summary    : The mhash library provides an easy way to access strong hashes,
description: |
    The mhash library provides an easy way to access strong hashes such as MD5, SHA1 and other algorithms.
builddeps  :
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
